### ISSUE TITLE
How to expose lightning and bitcoind JSON-RPC interfaces  

### ISSUE THREAD

**Issue by tiero** [NicolasDorier/lightning-charge-azure#1]

**Comment by NicolasDorier** [comment]
you have access to bitcoind and lightningd through `bitcoin-cli.sh` and `lightning-cli.sh` keep in mind I will soon update this repo with new version on Lightning which might break your stuff though.

**Comment by tiero** [comment]
Ok, I want to start bitcoind with the parameter `server=1`

I'm not a Docker user, do you think I can do it myself?

**Comment by tiero** [comment]
moreover I want to attach this package, but I don't know where I can find the `.lightning` file 

https://github.com/BHBNETWORK/lightning-client-js

Thank you in advance

**Comment by NicolasDorier** [comment]
@tiero you are on the lightning-charge-azure repo, not the lightning-charge repo. You have to use docker for hosting on azure. I can't provide do step to do without.

`server=1` is not needed with bitcoind. It is on by default.

**Comment by tiero** [comment]
Thank you for the confirmation
